Repository ayshiff/madu_gr_4, pull requests merged in 2020-02, with the labels that each got.

#11 [Services] - Add commun services
  client/.env.development
  client/src/madu/app-config.ts
  client/src/madu/apps/poi/index.tsx
  client/src/madu/services/commun/index.ts
  client/src/madu/services/commun/types.ts
  client/yarn.lock
Labels: Front, to-review

#20 add ci frozen-lock attr on yarn install
  .circleci/config.yml
Labels: to-review

#23 WIP: Feat: Back-end
  back-end/README.md
  back-end/docker-compose.yml
  back-end/src/app.controller.ts
  back-end/src/app.module.ts
  back-end/src/auth/auth.module.ts
  back-end/src/auth/auth.service.ts
  back-end/src/auth/dto/login.dto.ts
  back-end/src/auth/guards/auth.guard.ts
  back-end/src/auth/guards/roles.guard.ts
  back-end/src/auth/jwt.strategy.ts
  back-end/src/auth/userRole.enum.ts
  back-end/src/company/company.controller.ts
  back-end/src/company/company.module.ts
  back-end/src/company/company.service.ts
  back-end/src/company/dto/create-company.dto.ts
  back-end/src/company/interfaces/company.interface.ts
  back-end/src/company/model/company-status.enum.ts
  back-end/src/company/schemas/company.schema.ts
  back-end/src/greenscore/dto/create-question.dto.ts
  back-end/src/greenscore/dto/create-template.dto.ts
  back-end/src/greenscore/greenscore.controller.spec.ts
  back-end/src/greenscore/greenscore.controller.ts
  back-end/src/greenscore/greenscore.module.ts
  back-end/src/greenscore/interfaces/question.interface.ts
  back-end/src/greenscore/interfaces/template.interface.ts
  back-end/src/greenscore/question.service.ts
  back-end/src/greenscore/schemas/question.schema.ts
  back-end/src/greenscore/schemas/template.schema.ts
  back-end/src/greenscore/template.service.ts
  back-end/src/greenscore/validator/TemplateValidationPipe.ts
  back-end/src/interceptor/data-formatter.interceptor.ts
  back-end/src/main.ts
  back-end/src/poi/dto/answer-poi-greenscore.dto.ts
  back-end/src/poi/dto/create-poi-greenscore.dto.ts
  back-end/src/poi/dto/create-poi.dto.ts
  back-end/src/poi/dto/update-poi.dto.ts
  back-end/src/poi/dto/validate-poi-greenscore.dto.ts
  back-end/src/poi/interfaces/poi.interface.ts
  back-end/src/poi/model/poi-status.enum.ts
  back-end/src/poi/poi.controller.spec.ts
  back-end/src/poi/poi.controller.ts
  back-end/src/poi/poi.module.ts
  back-end/src/poi/poi.service.spec.ts
  back-end/src/poi/poi.service.ts
  back-end/src/poi/schemas/poi.schema.ts
  back-end/src/users/dto/create-admin.dto.ts
  back-end/src/users/schemas/user.schema.ts
  back-end/src/users/user.controller.ts
  back-end/src/users/users.module.ts
  back-end/src/users/users.service.ts
Labels: Back

#14 WIP: test(mobx): add mobx store tests
  .circleci/config.yml
  README.md
  client/.coveralls.yml
  client/.env.development
  client/package-lock.json
  client/package.json
  client/src/madu/App.js
  client/src/madu/apps/poi/createPoi/index.tsx
  client/src/madu/apps/poi/createPoi/steps/step-one.tsx
  client/src/madu/apps/poi/createPoi/steps/step-two.tsx
  client/src/madu/apps/poi/listPoi/index.tsx
  client/src/madu/contexts/index.tsx
  client/src/madu/hooks/use-store.tsx
  client/src/madu/services/commun/index.ts
  client/src/madu/stores/clientStore/index.test.ts
  client/src/madu/stores/clientStore/index.ts
  client/src/madu/stores/clientStore/mock.ts
  client/src/madu/stores/companyStore/index.test.ts
  client/src/madu/stores/companyStore/index.ts
  client/src/madu/stores/companyStore/mock.ts
  client/src/madu/stores/index.ts
  client/src/madu/stores/pointOfInterestStore/index.test.ts
  client/src/madu/stores/pointOfInterestStore/index.ts
  client/src/madu/stores/pointOfInterestStore/mock.ts
  client/src/madu/stores/questionStore/index.test.ts
  client/src/madu/stores/questionStore/index.ts
  client/src/madu/stores/questionStore/mock.ts
  client/src/madu/stores/templateStore/index.test.ts
  client/src/madu/stores/templateStore/index.ts
  client/src/madu/stores/templateStore/mock.ts
  client/src/madu/stores/utils/autoSave.ts
  client/src/madu/stores/utils/index.ts
  client/tsconfig.json
  client/yarn.lock
Labels: Front, enhancement, wip

#39 Correction deploydockercompose playbook ansible
  .cloud/ansible/roles/deploydockercompose/tasks/main.yml
Labels: Infra

#41 Refactor Terraform deployment files
  .cloud/terraform/provider.tf
  .cloud/terraform/security_group.tf
  .cloud/terraform/server.tf
  .cloud/terraform/ssh_key.tf
Labels: Infra

#42 Eh/authentification
  back-end/package-lock.json
  client/package.json
  client/src/custom-broascast-channel.ts
  client/src/index.tsx
  client/src/madu/app-config.ts
  client/src/madu/apps/map/searchSidebar/searchSidebar.tsx
  client/src/madu/apps/poi/createPoi/index.tsx
  client/src/madu/apps/poi/createPoi/steps/step-two.tsx
  client/src/madu/main.js
  client/src/madu/services/commun/index.ts
  client/src/madu/services/commun/types.ts
  client/src/madu/services/login/index.ts
  client/src/madu/services/login/reader.ts
  client/src/madu/services/login/routes.ts
  client/src/madu/services/login/types.ts
  client/src/madu/services/login/writer.ts
  client/src/madu/startup.tsx
  client/src/outside-components.tsx
  client/src/styles/index.ts
  client/src/styles/molecules/template.tsx
  client/src/token-manager.ts
  client/src/typed-index.tsx
  client/yarn.lock
Labels: to-review

#33 Feature/cloud
  .cloud/README.md
  .cloud/ansible/deploydockercompose.yml
  .cloud/ansible/deployment.yml
  .cloud/ansible/installdocker.yml
  .cloud/ansible/inventory/group_vars/all.yml
  .cloud/ansible/inventory/group_vars/local.yml
  .cloud/ansible/roles/deploydockercompose/files/docker-compose.yml
  .cloud/ansible/roles/deploydockercompose/tasks/main.yml
  .cloud/ansible/roles/updatedockerfile/tasks/main.yml
  .cloud/ansible/updatedockerfile.yml
  .cloud/requirement.txt
  .cloud/terraform/deployment.tf
  .cloud/terraform/provider.tf
  .cloud/terraform/security_group.tf
  .cloud/terraform/server.tf
  .cloud/terraform/ssh_key.tf
  back-end/Dockerfile
  back-end/docker-compose.yml
  client/src/madu/apps/poi/index.tsx
Labels: Infra, to-review
