Repository ayshiff/madu_gr_4, pull requests merged in 2020-01, with the labels that each got.

#5 WIP: feat(chore): add tslint- prettier - pre-commit
  .circleci/config.yml
  README.md
  client/.eslintignore
  client/.eslintrc.js
  client/.prettierrc.js
  client/config/env.js
  client/config/jest/cssTransform.js
  client/config/jest/fileTransform.js
  client/config/modules.js
  client/config/paths.js
  client/config/pnpTs.js
  client/config/webpack.config.js
  client/config/webpackDevServer.config.js
  client/package-lock.json
  client/package.json
  client/scripts/build.js
  client/scripts/start.js
  client/scripts/test.js
  client/src/App.tsx
  client/src/config/store.ts
  client/src/epics/index.ts
  client/src/index.tsx
  client/src/react-app-env.d.ts
  client/src/reducers/index.ts
  client/src/serviceWorker.ts
  client/src/test/pages/App.test.tsx
  client/src/test/setup/fileMock.js
  client/src/test/setup/test-setup.js
  client/src/test/setup/test-shim.js
  client/tslint.json
  package-lock.json
Labels: enhancement

#12 Add ansible deployment script
  .cloud/ansible/deploydockercompose.yml
  .cloud/ansible/installdocker.yml
  .cloud/ansible/inventory/ec2.ini
  .cloud/ansible/inventory/group_vars/installdocker.yml
  .cloud/ansible/inventory/group_vars/tag_Name_serveur_madu.yml
  .cloud/ansible/inventory/inventory.ini
  .cloud/ansible/roles/deploydockercompose/files/docker-compose.yml
  .cloud/ansible/roles/deploydockercompose/tasks/main.yml
  .cloud/ansible/roles/installdocker/tasks/main.yml
  .cloud/terraform/deployment.tf
  .cloud/terraform/terraform.tfvars
  .cloud/terraform/variables.tf
Labels: Infra, enhancement

#18 Merge feature/back-end
  .cloud/ansible/inventory/group_vars/local.yml
  .cloud/ansible/inventory/inventory
  .cloud/ansible/inventory/inventory.ini
  .cloud/ansible/roles/updatedockerfile/tasks/main.yml
  .cloud/ansible/updatedockerfile.yml
  back-end/.gitignore
  back-end/README.md
  back-end/docker-compose.yml
  back-end/nest-cli.json
  back-end/package-lock.json
  back-end/package.json
  back-end/src/app.controller.spec.ts
  back-end/src/app.controller.ts
  back-end/src/app.module.ts
  back-end/src/auth/auth.module.ts
  back-end/src/auth/auth.service.spec.ts
  back-end/src/auth/auth.service.ts
  back-end/src/auth/constants.ts
  back-end/src/auth/decorator/roles.decorator.ts
  back-end/src/auth/guards/roles.guard.ts
  back-end/src/auth/jwt.strategy.ts
  back-end/src/auth/local.strategy.ts
  back-end/src/company/company.controller.spec.ts
  back-end/src/company/company.controller.ts
  back-end/src/company/company.module.ts
  back-end/src/company/company.service.ts
  back-end/src/company/dto/create-company.dto.ts
  back-end/src/company/interfaces/company.interface.ts
  back-end/src/company/schemas/company.schema.ts
  back-end/src/main.ts
  back-end/src/users/dto/create-user.dto.ts
  back-end/src/users/interfaces/user.interface.ts
  back-end/src/users/pipes/CustomValidationPipe.ts
  back-end/src/users/schemas/user.schema.ts
  back-end/src/users/user.controller.spec.ts
  back-end/src/users/user.controller.ts
  back-end/src/users/users.module.ts
  back-end/src/users/users.service.spec.ts
  back-end/src/users/users.service.ts
  back-end/test/app.e2e-spec.ts
  back-end/test/jest-e2e.json
  back-end/tsconfig.build.json
  back-end/tsconfig.json
  client/Dockerfile
Labels: Back, Infra, enhancement

#16 Add P.O.I interface
  client/src/madu/App.js
  client/src/madu/apps/poi/createPoi/form/formstep1.tsx
  client/src/madu/apps/poi/createPoi/form/formstep2.tsx
  client/src/madu/apps/poi/createPoi/form/formstep3.tsx
  client/src/madu/apps/poi/createPoi/form/formstep4.tsx
  client/src/madu/apps/poi/createPoi/index.tsx
  client/src/madu/apps/poi/index.tsx
  client/src/madu/apps/poi/listPoi/index.tsx
Labels: Front, enhancement, wip
